spring.application.name=payment-gateway
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentgateway
spring.datasource.username=${DB_USERNAME:paymentgateway}
spring.datasource.password=${DB_PASSWORD:paymentgateway}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
